YOLO:
  YOLO_WEIGHTS: 'yolov8x-seg'
INPUT:
  FOLDER: 'D:/INTEIA/Videos/Pruebas/Aforo_Bus/'
  FILE: 'sgtcootransvi.dyndns.org_01_2023051112113649.mp4'
DETECTION:
  # CLASS_FILTER: [0,1,2,3,5,7]
  CLASS_FILTER: [65,67]
  CONFIDENCE: 0.4
DRAW:
  BOXES: True
  LABELS: True
  TRACKS: True
  MASKS: True
SHOW: True
SAVE:
  VIDEO: True
  CSV: True
  